### ISSUE TITLE
Add style for section when width is between 769px and 992px, when there are no anchors

### ISSUE THREAD

**Issue by uglow** [swanky-docs/swanky-theme#22]
I noticed this on the Components page of the demo site. The content was not positioned properly between 769px and 992px.

If you insert this code into https://github.com/swanky-docs/swanky-theme/blob/master/css/layouts/default.styl#L12, it fixes the issue. The code is copied from line 18 😄 

``` css
@media screen and (min-width: $screen-is-bigger-than-tablet)
      padding 160px 40px 40px ($sidebar-width + 60)px
```

**Comment by rodleviton** [comment]
Fixed
